name: "KubeOne"

on:
  push:
    branches:
      - main

jobs:
  test:
    name: "Test kubeval"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["v1.3.2", "master", "v1.0.0"]
    steps:
      - name: Kubeval
        id: kubeval
        uses: cedi/gh-action-install-kubeval@main
        with:
          version: ${{ matrix.version }}

      - name: Print version
        shell: bash
        run: echo "kubeval Version is ${{ steps.kubeval.outputs.version }}"

  doubleinstall:
    name: "Test installing twice"
    runs-on: ubuntu-latest
    steps:
      - name: One
        uses: cedi/gh-action-install-kubeval@main

      - name: Two
        id: kubeval
        uses: cedi/gh-action-install-kubeval@main

      - name: Print version
        shell: bash
        run: echo "kubeval Version is ${{ steps.kubeval.outputs.version }}"
